### ISSUE TITLE
Emulator display layout awkward on Firefox 81.0 (64-bit) on Ubuntu 20.04

### ISSUE THREAD

**Issue by rundel-tech** [maly/asm80-node#13]
The issue is best described by this screenshot:

![Screenshot from 2020-10-14 12-49-47](https://user-images.githubusercontent.com/67599918/95985219-3e2de380-0e1c-11eb-8d99-c68f78b4f290.png)

Depending on screen size, the blue bar at the bottom obscures either the H'L' register (in Z80 mode) or the Single Step button. This makes the emulator very hard to use. Is there some way I can adjust the left-hand column to add more space, or perhaps use a different (smaller) font?

**Comment by maly** [comment]
I believe it is fixed now, please check and re-open, if needed.

**Comment by rundel-tech** [comment]
Much better! Thanks for your quick fix.

![Screenshot from 2020-10-21 13-38-48](https://user-images.githubusercontent.com/67599918/96720712-02a69280-13a3-11eb-9547-274b467ed1ae.png)

**Comment by maly** [comment]
You're welcome!
