### ISSUE TITLE
Entry Point Not Found in Windows XP X64

### ISSUE THREAD

**Issue by Vaklin** [maly/asm80-node#7]
Hi!
I really want to try and use in the future your software. Unfortunately, I got a message "The procedure entry point ReleaseSRWLockExclusive could not be located in the dynamic link library KERNEL32.DLL".

Is possible to do something in this case?

**Comment by maly** [comment]
It refers to the Node.js error. Can you please test the "node --version" or update the node.js environment? Thanks
