### ISSUE TITLE
6502 Assembler ignoring 1-byte instructions

### ISSUE THREAD

**Issue by NullMember** [maly/asm80-node#8]
Hi. Your project is awesome. Thank you for your hard work.
Probably latest commit broke 6502 assembler. All 1-byte instructions are ignored. Here is example:

>LDX #0xFF
LOOP:
CLC
INX
DEY
BNE LOOP

Listing:

> 0000   A2 FF                  LDX   #0xFF   
0002                LOOP:        
0002   00                     CLC      
0002   00                     INX      
0002   00                     DEY      
0002   D0 FE                  BNE   LOOP   
LOOP:               0002 DEFINED AT LINE 2
                    > USED AT LINE 6

**Comment by maly** [comment]
It should be fixed now, commit #fa4f92e, version 1.8.1
